
spring.application.name=demoChat
spring.ai.google.genai.api-key = ${API_KEY}
spring.ai.google.genai.chat.options.model = gemini-2.5-flash



spring.datasource.url=jdbc:mysql://9ov50l.h.filess.io:61001/hrithikDB_leathermad?useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=hrithikDB_leathermad
spring.datasource.password=33684f489651f354e8822e068df1ab167f7b5ba1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never

jwt.secret=2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2
jwt.expiration=360000

spring.security.user.name=user
spring.security.user.password=1234

server.port=${PORT:8080}



